# Use our docker with boost built
image: registry.gitlab.com/manchester_qbi/manchester_qbi_public/madym_cxx

stages:
  - fetch-version
  - build
  - test
  - build_dist
  - test_dist
  - deploy

before_script:
  - git fetch --tags

fetch-semantic-version:
  # Requires Node >= 10.13 version
  image: node:13
  stage: fetch-version
  only:
    refs:
    - master
    - /^release-.*$/
  script:
    - npm install @semantic-release/gitlab @semantic-release/exec @semantic-release/changelog
    - npx semantic-release

build:
  stage: build
  script:
    - echo "This job builds madym in debug configuration for testing"
    - mkdir -p build
    - cd build
    - cmake .. \
        -DCMAKE_BUILD_TYPE=Debug \
        -D BUILD_DOCUMENTATION=OFF \
        -D BUILD_INSTALL=OFF \
        -D BUILD_QT_GUI=ON \
        -D BUILD_SHARED_LIBS=ON \
        -D BUILD_TESTING=ON \
        -D BUILD_TOOLS=ON \
        -D BUILD_WITH_DCMTK=ON \
        -D BUILD_WITH_ZLIB=ON
    - make
    - echo "Madym version is $(bin/madym_DCE -v)"
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - build/
  artifacts:
    paths:
    - build/
    expire_in: 1 week
  only:
    - master
    - merge_requests
    - /^release-.*$/

test:
  stage: test
  script:
    - echo "This job tests madym in debug configuration"
    - cd build
    - ctest --verbose
  only:
    - master
    - merge_requests
    - /^[0-9]+-[0-9]+-release$/

build_dist:
  stage: build_dist
  script:
    - echo "This job builds madym in release configuration for distribution"
    - mkdir dist
    - cd dist
    - cmake .. \
        -D BUILD_DOCUMENTATION=OFF \
        -D BUILD_INSTALL=OFF \
        -D BUILD_QT_GUI=ON \
        -D BUILD_SHARED_LIBS=ON \
        -D BUILD_TESTING=ON \
        -D BUILD_TOOLS=ON \
        -D BUILD_WITH_DCMTK=ON \
        -D BUILD_WITH_ZLIB=ON
    - make
  artifacts:
    paths:
      - dist/
  only:
  - /^[0-9]+-[0-9]+-release$/

test_dist:
  stage: test_dist
  script:
    - echo "This job tests madym in release configuration for distribution"
    - cd dist
    - ctest --verbose
  only:
    - /^[0-9]+-[0-9]+-release$/

deploy:
  stage: deploy
  script: 
    - echo "Make intall and package"
    - cd dist
    - make install
    - make package
  artifacts:
    paths:
      - deploy/
      - madym_v*.deb
      - madym_v*.tar.gz
      - madym_v*.exe
  #environment:
  #  name: staging
  #  url: https://staging.example.com
  only:
    - /^[0-9]+-[0-9]+-release$/
  
