# Use our docker with boost built
image: registry.gitlab.com/manchester_qbi/manchester_qbi_public/madym_cxx

build_madym:
  # Build the application
  stage: build
  script:
    - echo "This job builds madym"
    - mkdir build
    - cd build
    - cmake ..
    - make
    - bin/madym_DCE -v
    - bin/test_mdm
    - bin/test_mdm_tools

test_madym:
  stage: test
  script:
    - echo "This job tests madym"
    - ls
    - ctest
    - echo "build stage are complete."