# Use our docker with boost built
image: registry.gitlab.com/manchester_qbi/manchester_qbi_public/madym_cxx/madym_depends

stages:
  - fetch-version
  - build
  - test
  - build_dist
  - test_dist
  - deploy

before_script:
  - git fetch --tags

fetch-semantic-version:
  # Requires Node >= 10.13 version
  image: node:13
  stage: fetch-version
  only:
    refs:
    - master
    - /^release-.*$/
  script:
    - npm install @semantic-release/gitlab @semantic-release/exec @semantic-release/changelog
    - npx semantic-release

build:
  stage: build
  script:
    - echo "This job builds madym in debug configuration for testing"
    - mkdir -p build
    - cmake 
        -D CMAKE_BUILD_TYPE=Debug 
        -D BUILD_DOCUMENTATION=ON 
        -D BUILD_INSTALL=OFF 
        -D BUILD_QT_GUI=ON 
        -D BUILD_SHARED_LIBS=ON 
        -D BUILD_TESTING=ON 
        -D BUILD_TOOLS=ON 
        -D BUILD_WITH_DCMTK=ON 
        -D BUILD_WITH_ZLIB=ON 
        -S ../madym_cxx 
        -B build
    - cd build
    - ls
    - make
    - echo "Madym version is $(bin/madym_DCE -v)"
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - build/
  artifacts:
    paths:
    - build/
    expire_in: 1 week
  only:
    - master
    - merge_requests
    - /^release-.*$/

test:
  stage: test
  script:
    - echo "This job tests madym in debug configuration"
    - cd build
    - ctest --verbose
  only:
    - master
    - merge_requests
    - /^release-.*$/

build_dist:
  stage: build_dist
  script:
    - echo "This job builds madym in release configuration for distribution"
    - mkdir ../dist
    - cd ../dist
    - cmake \
        -D CMAKE_C_COMPILER=$CC
        -D CMAKE_CXX_COMPILER=$CXX
        -D CMAKE_BUILD_TYPE=Release
        -D BUILD_DOCUMENTATION=OFF
        -D BUILD_INSTALL=OFF
        -D BUILD_QT_GUI=ON
        -D BUILD_SHARED_LIBS=ON
        -D BUILD_TESTING=ON
        -D BUILD_TOOLS=ON
        -D BUILD_WITH_DCMTK=ON
        -D BUILD_WITH_ZLIB=ON
        -S ../madym_cxx
    - make
  artifacts:
    paths:
      - ../dist/
  only:
  - /^release-.*$/

pages:
  stage: build_dist
  script:
  - doxygen build/doxyfile
  - mv /builds/manchester_qbi/manchester_qbi_public/madym_cxx/build/docs/html/ public/
  - cp /builds/manchester_qbi/manchester_qbi_public/madym_cxx/madym_lrg.png public/
  artifacts:
    paths:
    - public
  only:
    - master
    - /^release-.*$/

test_dist:
  stage: test_dist
  script:
    - echo "This job tests madym in release configuration for distribution"
    - cd ../dist
    - ctest --verbose
  only:
    - /^release-.*$/

deploy:
  stage: deploy
  script: 
    - echo "Make intall and package"
    - cd ../dist
    - make install
    - make package
  artifacts:
    paths:
      - deploy/
      - madym_v*.deb
      - madym_v*.tar.gz
      - madym_v*.exe
  #environment:
  #  name: staging
  #  url: https://staging.example.com
  only:
    - /^release-.*$/
  
