# Use the official gcc image
image: gcc

before_script:
  # Install build dependencies
  - apt-get update
  - apt-get install --yes
      wget cmake build-essential
      libboost-all-dev

build_madym:
  # Build the application
  stage: build
  script:
    - echo "This job builds madym"
    #- mkdir build
    #- cd build
    #- cmake ..
    #- make

test_madym:
  stage: test
  script:
    - echo "This job tests madym"
    - echo "build stage are complete."