# Use our docker with boost built
image: registry.gitlab.com/manchester_qbi/manchester_qbi_public/madym_cxx

before_script:
  - git fetch --tags

build:
  stage: build
  script:
    - echo "This job builds madym"
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
    - build/
    expire_in: 1 week
  only:
    - master
    - merge_requests
    - /^release-.*$/
  variables:
    GIT_FETCH_EXTRA_FLAGS: --tags

test:
  stage: test
  script:
    - ls
  only:
    - merge_requests
    - /^release-.*$/

deploy:
  stage: deploy
  script: 
    - echo "Deploying code"
  only:
    - /^release-.*$/
  