# Use our docker with boost built
image: registry.gitlab.com/manchester_qbi/manchester_qbi_public/madym_cxx

before_script:
  - git fetch --tags

build:
  stage: build
  script:
    - echo "This job builds madym"
    - mkdir -p build
    - cd build
    - cmake ..
    - make
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - build/
  artifacts:
    paths:
    - build/
    expire_in: 1 week
  only:
    - master
    - merge_requests
    - /^release-.*$/
  variables:
    GIT_FETCH_EXTRA_FLAGS: --tags

test:
  stage: test
  script:
    - ls
    - cd build
    - ctest --verbose
  only:
    - master
    - merge_requests
    - /^release-.*$/

build_dist:
  stage: deploy
  script:
    - echo "This job builds madym for distribution"
    - mkdir dist
    - echo "madym release" >> dist/release.txt
  artifacts:
    paths:
      - dist/
  only:
  - /^release-.*$/

deploy:
  stage: deploy
  script: 
    - echo "Deploying code"
    - echo "Do something with the stuff in /dist"
  only:
    - /^release-.*$/
  