# Use the official gcc image
image: gcc

before_script:
    # Install build dependencies
    - apt-get update && apt-get -y install cmake

build_madym:
    # Build the application
    stage: build
    script:
        #- mkdir build
        #- cd build
        #- cmake ..
        #- make
        - echo "This job builds madym"

test_madym:
  stage: test
  script:
    - echo "This job tests madym"
    - echo "build stage are complete."